name: Deploy to decker

on:
  push:
    branches:
      - main
    
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag my-ai-model:latest ${{ secrets.DOCKER_USERNAME }}/ai-test:my-test-model
        docker push ${{ secrets.DOCKER_USERNAME }}/ai-test:my-test-model
    
    - name: Build Docker image
      run: docker build -t my-test-model .

    - name: run docker
      run: docker run -d -p 8088:3000 --name test-container my-test-model

    - name: Verify runinng
      run: docker ps
